version: "3"

services: 
    mongo:
        image: mongo
        ports:
            - "27017:27017"
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - mongo
            - postgres
